{% set name = "igraph" %}
{% set version = "0.9.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/igraph/igraph/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 012e5d5a50420420588c33ec114c6b3000ccde544db3f25c282c1931c462ad7a
  patches:
    - correct-test-path.patch
    - 0001-feat-allow-external-f2c-arith.h-headers-when-cross-c.patch
    - 0002-tests-CMake-added-pre-existing-linker-flags.patch

build:
  skip: True  # [win and vc<14]
  number: 0
  script_env:
   - INTERNAL_ARPACK=0
   - INTERNAL_ARPACK=1  # [arm64]
   - F2C_EXTERNAL_ARITH_HEADER={{ RECIPE_DIR }}/arith_arm64.h  # [arm64]

  run_exports:
    - {{ pin_subpackage("igraph", max_pin="x.x") }}

requirements:
  build:
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - vs2017_{{ target_platform }}  # [win]
    - cmake
    - ninja
    - make  # [not win]
    - python  # [win]
    - pkg-config  # [not win]
  host:
    - glpk
    - libxml2
    - suitesparse
    - arpack   # [not arm64]
    - gmp  # [not win]
    - mpir  # [win]
    - libblas
    - liblapack
  run:
    - glpk
    - libxml2
    - suitesparse
    - arpack  # [not arm64]
    - gmp  # [not win]
    - mpir  # [win]

test:
  files:
    - igraph_test.c
  requires:
    - pkg-config  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - vs2017_{{ target_platform }}  # [win]
  commands:
    - pkg-config --exists igraph  # [not win]
    - pkg-config --libs --cflags igraph  # [not win]

about:
  home: http://igraph.org/c/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file:
    - COPYING
    - ACKNOWLEDGEMENTS.md
  summary: 'An open source and free collection of network analysis tool.'
  description: |
    igraph is a collection of network analysis tools with the emphasis on efficiency,
    portabiliy and ease of use. igraph is open source and free. igraph can be
    programmed in R, Python and C/C++."

extra:
  recipe-maintainers:
    - sodre
    - vtraag
