{%set name = "igraph" %}
{%set version = "0.7.1" %}
{%set sha256 = "806a3e667913c711f41a3b8e88642e81d1529ac8285f1c65126add7f1254a864" %}
{%set sha256win = "x" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  url: https://github.com/igraph/{{ name }}/archive/{{ version }}.tar.gz  # [not win]
  sha256: {{ sha256 }}  # [not win]

  fn: {{ name }}-{{ version }}.zip  # [win]
  url: https://github.com/igraph/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}-msvc.zip  # [win]
  sha256: {{ sha256win }}  # [not win]

  patches:
    # Get version from environment variable
    - 00-tools-getversion.patch  # [not win]
    # Enable PRPACK_IGRAPH_SUPPORT (c.f. stackoverflow/25260025)
    - 02-enable-prpack-igraph-support.patch  # [win]
    # VC14 ship with snprintf
    - 03-disable-snprintf-macro.patch  # [win]

    # fixes igraph/igraph#906
    - b215195214abb8355121a8430c86df04e1f00eae.patch  # [not win]
    - 0387a58419552aa69be2ac6aaa2f77ad8d6e9add.patch  # [osx]
    # fixes igraph/igraph#857
    - ca8355ae35e05570ee56ac354a4146c0c8f7a8ec.patch  # [not win]

build:
  skip: True  # [win and py27]
  number: 4
  features:
    - vc9   # [win and py27]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - autoconf  # [not win]
    - automake  # [not win]
    - bison  # [not win]
    - flex  # [not win]
    - gmp >=5.0.1,<7  # [not win]
    - libtool  # [not win]
    - pkg-config  # [not win]

    - toolchain
    - libxml2 2.9.*

    - python  # [win]

    - m2-autoconf  # [win]
    - m2-automake1.15 # [win]
    - m2-automake-wrapper # [win]
    - m2-bison  # [win]
    - m2-flex  # [win]
    - m2w64-gcc  # [win]
    - m2-libtool  # [win]
    - msinttypes  # [win]
    - posix # [win]
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 or py36)]
  run:
    - gmp >=5.0.1,<7  # [not win]
    - libxml2 2.9.*

    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 or py36)]

test:
  files:
    - igraph_test.c
  requires:
    - pkg-config  # [not win]
    - toolchain   # [not win]
  commands:
    - pkg-config --exists igraph  # [not win]

about:
  home: http://igraph.org
  license: GPL2
  license_family: GPL
  license_file: COPYING
  summary: 'An open source and free collection of network analysis tool.'
  description: |
    igraph is a collection of network analysis tools with the emphasis on efficiency,
    portabiliy and ease of use. igraph is open source and free. igraph can be
    programmed in R, Python and C/C++."

extra:
  recipe-maintainers:
    - sodre
