{% set name = "igraph" %}
{% set version = "0.9.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/igraph/igraph/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 012e5d5a50420420588c33ec114c6b3000ccde544db3f25c282c1931c462ad7a

build:
  skip: True  # [win and vc<14]
  number: 0
  run_exports:
    - {{ pin_subpackage("igraph", max_pin="x.x") }}

requirements:
  build:
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - vs2017_{{ target_platform }}  # [win]
    - cmake
    - ninja
    - make  # [not win]
    - python  # [win]
    - pkg-config  # [not win]
    - glpk
    - openblas
    - suitesparse
    - libxml2
    - arpack
    - gmp  # [not win]
  host:
    - icu  # [not win]
    - libiconv  # [not win]
    - xz  # [not win]
    - zlib  # [not win]
  run:
    - glpk
    - openblas
    - suitesparse
    - libxml2
    - arpack
    - gmp  # [not win]

test:
  requires:
    - pkg-config  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - vs2017_{{ target_platform }}  # [win]
    - cmake
  commands:
    - cd build && cmake --build . --target check

about:
  home: http://igraph.org/c/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file:
    - COPYING  # [not win]
    - ACKNOWLEDGEMENTS.md  # [not win]
  license_file:
    - '{{ environ["RECIPE_DIR"] }}/COPYING'  # [win]
    - '{{ environ["RECIPE_DIR"] }}/ACKNOWLEDGEMENTS.md'  # [win]
  summary: 'An open source and free collection of network analysis tool.'
  description: |
    igraph is a collection of network analysis tools with the emphasis on efficiency,
    portabiliy and ease of use. igraph is open source and free. igraph can be
    programmed in R, Python and C/C++."

extra:
  recipe-maintainers:
    - sodre
    - vtraag
